#This file stores configuration options for Iris, such as the currently active shaderpack
#Sat Aug 15 11:12:43 PDT 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=32
shaderPack=ComplementaryUnbound_r5.8.1 + EuphoriaPatches_1.9.3
